### ISSUE TITLE
NativeClient: could not create instance

### ISSUE THREAD

**Issue by shaded-enmity** [rpwoodbu/mosh-chrome#158]
I'm experiencing the following error when trying to run Mosh (0.4.5) on Windows 10 x32 box with Chrome 61.0.6163.100:

```
hterm_all.js:186 init: hterm
mosh_window.html:1 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm_all.js:4406:27)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm_all.js:13515:22)
    at Object.callback (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:112:30)
    at mosh.CommandInstance.run (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:110:23)
    at hterm.Terminal.runCommandClass (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm_all.js:10977:16)
    at hterm.Terminal.terminal.onTerminalReady (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:34:14)
    at hterm.Terminal.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm_all.js:10465:37)
    at hterm.Terminal.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm_all.js:10856:7)
mosh_window.html:1 NativeClient: could not create instance.
```

**Comment by rpwoodbu** [comment]
You said "x32"... Are you saying you're running a 32-bit machine? I wouldn't be at all surprised if NaCl is broken in Chrome on 32-bit. Can you run other NaCl apps, such as Secure Shell?

**Comment by shaded-enmity** [comment]
32bit version of Windows, the CPU is x64 Atom. Secure shell works fine.

**Comment by rpwoodbu** [comment]
Hmm, interesting that Secure Shell is working OK. You might try installing "Mosh (dev)" from the store, and seeing if that works better. I've seen bugs building for ARM, so maybe there are bugs building for i686, too.
