### ISSUE TITLE
Provide debugging info or expose logs

### ISSUE THREAD

**Issue by cccCody** [rpwoodbu/mosh-chrome#160]
I'm trying to connect to a machine with mosh server running, and after clicking connect, I just get a window that's empty except for a cursor, and doesn't respond to input. Is there a way to see more verbose info about the connection attempt? I don't know where to look for logs.

**Comment by rpwoodbu** [comment]
Whenever dealing with Chrome apps or extensions, always go to the JS console first and foremost for debugging info. (There's a tip in the [FAQ](https://github.com/rpwoodbu/mosh-chrome/wiki/FAQ) about how to do that.)

However, I doubt there will be any useful info there in this case. If the screen goes blank, and you don't see a blue banner at top complaining about anything, then mosh thinks it has established communication. Occasionally I have seen a bug whereby it needs a little "kick" by hitting `Enter`; not sure if that's a bug in mosh upstream or a bug in my POSIX socket code.

When you're at the blank screen, Mosh for Chrome is running the upstream mosh code. It doesn't provide much in the way of debug logs; see [here](https://github.com/mobile-shell/mosh/search?p=2&q=verbose&type=&utf8=%E2%9C%93) for all the places it might say something if `-v` were set. If something there might be useful, it wouldn't be too hard to turn on verbosity and have it dump to the JS console. It'd be nice if that could be left on at all times, but if it is really chatty, there could be a performance penalty.

**Comment by cccCody** [comment]
Thanks for the FAQ tip. I missed that. I'm not sure if this is my problem, but here's what's in my console after trying to connect:
```
init: hterm
mosh_window.html:1 Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm_all.js:4412:27)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm_all.js:13717:22)
    at Object.callback (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:112:30)
    at mosh.CommandInstance.run (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:110:23)
    at hterm.Terminal.runCommandClass (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm_all.js:11053:16)
    at hterm.Terminal.terminal.onTerminalReady (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/mosh_window.js:34:14)
    at hterm.Terminal.<anonymous> (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm_all.js:10524:37)
    at hterm.Terminal.<anonymous> (chrome-extension://hmgggebkhjjkiimkjlknpdgapncghehh/hterm_all.js:10915:7)
mosh_window.html:1 NativeClient: Nexe crashed during startup
```

**Comment by cccCody** [comment]
pull request: https://github.com/rpwoodbu/mosh-chrome/pull/161

**Comment by rpwoodbu** [comment]
Ah, a crash, huh? Eek. Do you happen to be on ARM? Can you also try the "Mosh (dev)" version?

I should do something to ensure these crashes are visible, and not just show a blank screen.

Thanks for the pull request. Things are in turmoil right now (in a good way, but still...), so I won't be able to test and merge that pull request for a few weeks probably.

**Comment by cccCody** [comment]
Nope, not on ARM. Plain ol' x86-64. I've tried the dev version as well and get the same Nexe crash.

**Comment by rpwoodbu** [comment]
This sounds like #124. I'll reopen that one, and repurpose this one to improve crash reporting. Please add comments there. In particular, I'd be curious as to which version of Windows you're running.
