### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by narrowfail** [rpwoodbu/mosh-chrome#91]
I just updated chrome to version Versión 42.0.2311.90m and when I launch the app and try to connect "Loading NaCl module (takes a while the first time after an update)." and won't do anything. I waited for 20 min and nothing.

Thanks!

**Comment by rpwoodbu** [comment]
I have very occasionally seen Chrome get stuck when loading NaCl modules. Usually restarting the app fixes the issue. Barring that, try completely restarting the browser. Let me know if that helps. If it doesn't, please also let me know what OS and CPU architecture you're running on.

**Comment by narrowfail** [comment]
Browser restarted, nothing happened. Im on Windows 8 x86-64.

**Comment by rpwoodbu** [comment]
This isn't reproducible on Windows 8.1 Pro. Can you open the Javascript console and copy/paste the contents? Maybe there's a hint in there. There are instructions on how to get to the Javascript console [here](https://github.com/rpwoodbu/mosh-chrome/wiki/FAQ#how-can-i-change-the-way-the-terminal-looks-font-color-etc).

**Comment by narrowfail** [comment]
Sure, here it is:
```
init: hterm
Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.lib.encodeUTF8 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm_deps.js:4388:26)
    at hterm.Terminal.IO.print.hterm.Terminal.IO.writeUTF16 (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:7787:22)
    at Object.callback (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:117:30)
    at mosh.CommandInstance.run (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:115:23)
    at hterm.Terminal.runCommandClass (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5256:16)
    at terminal.onTerminalReady (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/mosh_window.js:40:14)
    at null.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:4762:37)
    at null.<anonymous> (chrome-extension://ooiklbnjmhbcgemelgfhaeaocllobloj/hterm/hterm.js:5135:7)
NativeClient: PnaclCoordinator: Compile process could not be created: 
```

**Comment by rpwoodbu** [comment]
The first error is "expected"; there's something in hterm that causes that, but is innocuous.

The compile process thing is the rub. Is there not anything after the colon? This doesn't look like a Mosh error, but some sort of issue with Chrome's PNaCl framework. I'm not sure how much help I can be. You might try installing the dev version (called "Mosh (dev)" in the store) to see if it has the same problem. If not, you might try uninstalling and reinstalling the Mosh app. If it also fails, it would seem then to be a problem with your Chrome installation.

I should point out that this was not reproducible in the exact same version of Chrome as you're running. As this looks to be a problem with your machine, I'm going to go ahead and close this issue. Feel free to keep posting to this issue, though, if you have more questions, or want to let me know how you resolved it.
